name: Trigger Build on Linode via WebHook 

on:
  push:
    branches:
      - main  # Adjust this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.GH_PAT_CLIENT_HOOK}}" \
            https://api.github.com/repos/devprojectekla/NodeReactPlatform/dispatches \
            -d '{"event_type":"client-update"}'
